tasks:
- init: |
    sudo apt -y install cmake
    cmake -S. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    cmake --build build --target all 
    sudo apt-get install libomp-dev
  command: |
    export OMP_NUM_THREADS=8
    gcc -o test -fopenmp main.c
    ./test
vscode:
  extensions:
    - twxs.cmake
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cmake-tools
    - webfreak.debug
